export interface LanguageOption {
  code: string;
  name: string;
  nativeName?: string;
  group?: 'Special' | 'Popular' | 'All';
}

export const TRANSCRIPTION_LANGUAGES: LanguageOption[] = [
  // Special First Options
  { code: 'auto', name: '✨ Auto-Detect Language', group: 'Special' },
  { code: 'roman_urdu_hinglish', name: '🔥 Roman Urdu / Hinglish (Latin Script)', group: 'Special' },

  // Popular Languages
  { code: 'en', name: 'English', nativeName: 'English', group: 'Popular' },
  { code: 'ur', name: 'Urdu', nativeName: 'اردو', group: 'Popular' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', group: 'Popular' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', group: 'Popular' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', group: 'Popular' },
  { code: 'fr', name: 'French', nativeName: 'Français', group: 'Popular' },
  { code: 'de', name: 'German', nativeName: 'Deutsch', group: 'Popular' },
  { code: 'zh', name: 'Chinese (Mandarin)', nativeName: '中文', group: 'Popular' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語', group: 'Popular' },
  { code: 'ko', name: 'Korean', nativeName: '한국어', group: 'Popular' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português', group: 'Popular' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский', group: 'Popular' },
  { code: 'it', name: 'Italian', nativeName: 'Italiano', group: 'Popular' },
  { code: 'tr', name: 'Turkish', nativeName: 'Türkçe', group: 'Popular' },

  // Comprehensive Global Languages (All supported by Whisper)
  { code: 'af', name: 'Afrikaans', nativeName: 'Afrikaans', group: 'All' },
  { code: 'sq', name: 'Albanian', nativeName: 'Shqip', group: 'All' },
  { code: 'am', name: 'Amharic', nativeName: 'አማርኛ', group: 'All' },
  { code: 'hy', name: 'Armenian', nativeName: 'Հայերեն', group: 'All' },
  { code: 'az', name: 'Azerbaijani', nativeName: 'Azərbaycan', group: 'All' },
  { code: 'eu', name: 'Basque', nativeName: 'Euskara', group: 'All' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', group: 'All' },
  { code: 'bs', name: 'Bosnian', nativeName: 'Bosanski', group: 'All' },
  { code: 'bg', name: 'Bulgarian', nativeName: 'Български', group: 'All' },
  { code: 'my', name: 'Burmese', nativeName: 'မြန်မာဘာသာ', group: 'All' },
  { code: 'ca', name: 'Catalan', nativeName: 'Català', group: 'All' },
  { code: 'hr', name: 'Croatian', nativeName: 'Hrvatski', group: 'All' },
  { code: 'cs', name: 'Czech', nativeName: 'Čeština', group: 'All' },
  { code: 'da', name: 'Danish', nativeName: 'Dansk', group: 'All' },
  { code: 'nl', name: 'Dutch', nativeName: 'Nederlands', group: 'All' },
  { code: 'et', name: 'Estonian', nativeName: 'Eesti', group: 'All' },
  { code: 'fi', name: 'Finnish', nativeName: 'Suomi', group: 'All' },
  { code: 'gl', name: 'Galician', nativeName: 'Galego', group: 'All' },
  { code: 'ka', name: 'Georgian', nativeName: 'ქართული', group: 'All' },
  { code: 'el', name: 'Greek', nativeName: 'Ελληνικά', group: 'All' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', group: 'All' },
  { code: 'ha', name: 'Hausa', nativeName: 'Hausa', group: 'All' },
  { code: 'he', name: 'Hebrew', nativeName: 'עברית', group: 'All' },
  { code: 'hu', name: 'Hungarian', nativeName: 'Magyar', group: 'All' },
  { code: 'is', name: 'Icelandic', nativeName: 'Íslenska', group: 'All' },
  { code: 'id', name: 'Indonesian', nativeName: 'Bahasa Indonesia', group: 'All' },
  { code: 'ga', name: 'Irish', nativeName: 'Gaeilge', group: 'All' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', group: 'All' },
  { code: 'kk', name: 'Kazakh', nativeName: 'Қазақша', group: 'All' },
  { code: 'km', name: 'Khmer', nativeName: 'ខ្មែរ', group: 'All' },
  { code: 'lo', name: 'Lao', nativeName: 'ລາວ', group: 'All' },
  { code: 'lv', name: 'Latvian', nativeName: 'Latviešu', group: 'All' },
  { code: 'lt', name: 'Lithuanian', nativeName: 'Lietuvių', group: 'All' },
  { code: 'mk', name: 'Macedonian', nativeName: 'Македонски', group: 'All' },
  { code: 'ms', name: 'Malay', nativeName: 'Bahasa Melayu', group: 'All' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', group: 'All' },
  { code: 'mt', name: 'Maltese', nativeName: 'Malti', group: 'All' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', group: 'All' },
  { code: 'mn', name: 'Mongolian', nativeName: 'Монгол', group: 'All' },
  { code: 'ne', name: 'Nepali', nativeName: 'नेपाली', group: 'All' },
  { code: 'no', name: 'Norwegian', nativeName: 'Norsk', group: 'All' },
  { code: 'fa', name: 'Persian / Farsi', nativeName: 'فارسی', group: 'All' },
  { code: 'pl', name: 'Polish', nativeName: 'Polski', group: 'All' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', group: 'All' },
  { code: 'ro', name: 'Romanian', nativeName: 'Română', group: 'All' },
  { code: 'sr', name: 'Serbian', nativeName: 'Српски', group: 'All' },
  { code: 'si', name: 'Sinhala', nativeName: 'සිංහල', group: 'All' },
  { code: 'sk', name: 'Slovak', nativeName: 'Slovenčina', group: 'All' },
  { code: 'sl', name: 'Slovenian', nativeName: 'Slovenščina', group: 'All' },
  { code: 'so', name: 'Somali', nativeName: 'Soomaali', group: 'All' },
  { code: 'sw', name: 'Swahili', nativeName: 'Kiswahili', group: 'All' },
  { code: 'sv', name: 'Swedish', nativeName: 'Svenska', group: 'All' },
  { code: 'tl', name: 'Tagalog / Filipino', nativeName: 'Tagalog', group: 'All' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', group: 'All' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', group: 'All' },
  { code: 'th', name: 'Thai', nativeName: 'ไทย', group: 'All' },
  { code: 'uk', name: 'Ukrainian', nativeName: 'Українська', group: 'All' },
  { code: 'uz', name: 'Uzbek', nativeName: 'Oʻzbekcha', group: 'All' },
  { code: 'vi', name: 'Vietnamese', nativeName: 'Tiếng Việt', group: 'All' },
  { code: 'cy', name: 'Welsh', nativeName: 'Cymraeg', group: 'All' },
  { code: 'yo', name: 'Yoruba', nativeName: 'Èdè Yorùbá', group: 'All' },
  { code: 'zu', name: 'Zulu', nativeName: 'isiZulu', group: 'All' },
];
